#!/bin/bash

GPUFILE=/etc/asus_nvidia

if [ -f $GPUFILE ]; then
  echo "$GPUFILE exists."
  GPUFILEPRESENT=true
else
  echo "$GPUFILE does not exist."
  GPUFILEPRESENT=false
fi

if [[ $GPUFILEPRESENT == false ]]; then
  echo "set to Nvidia mode flag and restart GDM"
  systemctl stop gdm
  echo -n "0000:01:00.0" > /sys/bus/pci/drivers/nvidia/bind
  cp /etc/asusd/90-nvidia.conf /etc/X11/xorg.conf.d/90-nvidia.conf
  touch /etc/asus_nvidia
  asusctl -p normal
  systemctl restart gdm.service
else
  echo "deactivating nvidia"
  systemctl stop gdm
  echo -n "0000:01:00.0" > /sys/bus/pci/drivers/nvidia/unbind
  rm /etc/X11/xorg.conf.d/90-nvidia.conf
  rm /etc/asus_nvidia
  asusctl -p silent
  systemctl restart gdm.service
fi
