#!/bin/bash

GPUFILE=/etc/asus_nvidia

if [ -f $GPUFILE ]; then
  echo "$GPUFILE exists."
  GPUFILEPRESENT=true
else
  echo "$GPUFILE does not exist."
  GPUPRESENT=false
fi

if [ $GPUFILEPRESENT == true ]; then
  echo "Nvidia selected, choosing power profile normal"
  cp /etc/asusd/90-nvidia.conf /etc/X11/xorg.conf.d/90-nvidia.conf
  asusctl -p normal
else
  echo "AMD mode selected, unbinding nvidia and setting power profile to silent"
  rm /etc/X11/xorg.conf.d/90-nvidia.conf
  echo -n "0000:01:00.0" > /sys/bus/pci/drivers/nvidia/unbind
  asusctl -p silent
fi
