#!/bin/bash

GPUFILE=/etc/asus_nvidia

if [ -f $GPUFILE ]; then
  echo "$GPUFILE exists."
  GPUFILEPRESENT=true
else
  echo "$GPUFILE does not exist."
  GPUPRESENT=false
fi

if [ $GPUFILEPRESENT == true ]; then
  echo "activating and loading Nvidia"
  modprobe nvidia_uvm
  modprobe nvidia_drm
  modprobe nvidia_modeset
  modprobe nvidia
  asusctl -p normal
else
  echo "deactivating nvidia"
  sh -c 'echo "\\_SB.PCI0.GPP0.PG00._OFF" > /proc/acpi/call'
  asusctl -p silent
fi
