#!/usr/bin/sh

case $1 in
    pre)
	brightnessctl -d asus::kbd_backlight s 1
	brightnessctl -d asus::kbd_backlight s 0
	;;
    post)
        brightnessctl -d asus::kbd_backlight s 1
        brightnessctl -d asus::kbd_backlight s 0
	;;
esac
